### ISSUE TITLE
Bump electrum-client and esplora-client versions

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#1742]
Per @oleonardolima: "we'll need to publish a new release for rust-electrum-client (electrum-client) to have the fixed TLS version, and the id_pos (used for electrum vulnerability @LagginTimes is working on).

We'll probably need a new rust-esplora-client release as well, to publish the companion bdk_esplora with 1.0.0-beta without the async-std dependencies, as it has been removed in the latest esplora-client PR."

See:
- [x] bitcoindevkit/rust-electrum-client#150
- [x] bitcoindevkit/rust-electrum-client#155
- [x] bitcoindevkit/rust-esplora-client#103
- [x] bitcoindevkit/rust-electrum-client#156
- [x] bitcoindevkit/rust-esplora-client#112
- [x] #1751
- [x] #1746
