### ISSUE TITLE
Add missing docs 

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#192]
Prior to the `0.2.0` release we need to add missing rust docs. See the rust doc guild for [how to write documentation](https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html).  

To print missing doc warnings and open current docs in browser:
```shell
cargo doc --features all-keys,cli-utils,compiler,esplora,compact_filters --no-deps --open
```

To run tests in doc comments (only add features you're working on):
```shell
cargo test --features="all-keys,cli-utils,compiler,esplora,compact_filters" --doc
```

To format code in doc comments:
```shell
cargo +nightly fmt -- --config format_code_in_doc_comments=true
```

Please mention this issue and remove related TODOs in PRs to add missing docs. 

After all missing docs are added we will deny future builds with missing docs by adding to `lib.rs`:
```rust
#![deny(missing_docs)]
```

Current files with missing docs:

In-progress and completed:

- [x] blockchain/any.rs #197 #206
- [x] blockchain/compact_filters/mod.rs #214
- [x] blockchain/electrum.rs #197 #206
- [x] blockchain/esplora.rs #197 #206
- [x] cli.rs #194 
- [x] database/any.rs #214
- [x] descriptor/error.rs #214
- [x] error.rs #214 
- [x] lib.rs (also add high level overview similar to [tokio](https://docs.rs/tokio/0.3.4/tokio/index.html))
- [x] types.rs #214 
- [x] keys/mod.rs #220
- [x] keys/bip39.rs #220
- [x] descriptor/mod.rs #221
- [x] descriptor/policy.rs #221 
- [x] descriptor/template.rs #221 
- [x] wallet/address_validator.rs #223
- [x] wallet/coin_selection.rs #223
- [x] wallet/signer.rs #223
- [x] wallet/tx_builder.rs #223
- [x] wallet/mod.rs #223

**Comment by LLFourn** [comment]
An idea: Make a PR with `#![deny(missing_docs)]` and then we can gradually make PRs to that branch until CI passes.

**Comment by notmandatory** [comment]
I like that idea ! I'll set it up, starting with the `cli` module I've already started working on. I need to use `#![warn(missing_docs)]` instead of `deny` until we get them all fixed otherwise `doc` won't let us preview.

**Comment by justinmoon** [comment]
Another related idea would be to put a high-level overview (similar to what's currently in our README) in `lib.rs` so that it shows up on root page of `docs.rs`.

[Here's root of our docs now](https://bitcoindevkit.org/docs-rs/bdk/0.1.0-beta.1/bdk/) which lacks an overview, here's [tokio](https://docs.rs/tokio/0.3.4/tokio/index.html) which has a nice overview.

**Comment by notmandatory** [comment]
@justinmoon Good idea to also add overview in `lib.rs`. I'll add it to the checklist and see if I can borrow info from the README.md and the home page to flesh it out.

**Comment by notmandatory** [comment]
@LLFourn FYI I think it will be simpler if we just do docs changes as PRs directly into `master` branch as they get done. When when all are done I'll enable the `missing_docs` warning. I'm going to make a PR now for the changes that are ready to go in the `missing_docs` branch.

**Comment by notmandatory** [comment]
Only about a dozen warnings left for the `wallet` module so I just took them all, should have them ready to review tomorrow
