### ISSUE TITLE
Release 0.26.0

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#827]
### Summary

This release improves Fulcrum electrum server compatibility and fixes public descriptor template key origin paths. We also snuck in small enhancements to configure the electrum client to validate the domain using SSL and sort TransactionDetails by block height and timestamp.

### Commit

<--latest commit ID to include in this release-->

#### Fixed

* Make electrum blockchain client `save_tx` function order independent to work with Fulcrum servers. #808
* Fix wrong testnet key origin path in public descriptor templates. #818
* Make README.md code examples compile without errors. #820 

#### Added

* For electrum blockchain client, allow user to configure whether to validate the domain using SSL. #805
* Implement ordering for `TransactionDetails`. #812

#### Changed

* Bump `hwi` dependency to `0.4.0`. #825 
* Bump `esplora-client` dependency to `0.3` #830

### Checklist

Release numbering must follow [Semantic Versioning]. These steps assume the current `master`
branch **development** version is *0.25.0*.

#### On the day of the feature freeze

Change the `master` branch to the next MINOR+1 version:

- [x] Switch to the `master` branch.
- [x] Create a new PR branch called `bump_dev_0_26`, eg. `bump_dev_0_22`.
- [x] Bump the `bump_dev_0_26` branch to the next development MINOR+1 version.
  - Change the `Cargo.toml` version value to `0.26.0`.
  - The commit message should be "Bump version to 0.26.0".
- [x] Create PR and merge the `bump_dev_0_26` branch to `master`.
  - Title PR "Bump version to 0.26.0". #828 

Create a new release branch and release candidate tag:

- [x] Double check that your local `master` is up-to-date with the upstream repo.
- [x] Create a new branch called `release/0.26` from `master`.
- [x] Bump the `release/0.26` branch to `0.26.0-rc.1` version.
  - Change the `Cargo.toml` version value to `0.26.0-rc.1`.
  - The commit message should be "Bump version to 0.26.0-rc.1".
- [x] Add a tag to the `HEAD` commit in the `release/0.26` branch.
  - The tag name should be `v0.26.0-rc.1`
  - Use message "Release 0.26.0 rc.1".
  - Make sure the tag is signed, for extra safety use the explicit `--sign` flag.
- [x] Push the `release/0.26` branch and new tag to the `bitcoindevkit/bdk` repo.
  - Use `git push --tags` option to push the new `v0.26.0-rc.1` tag.

If any issues need to be fixed before the *0.26.0* version is released:

- [x] Merge fix PRs to the `master` branch.
- [x] Git cherry-pick fix commits to the `release/0.26` branch.
- [x] Verify fixes in `release/0.26` branch.
- [x] Bump the `release/0.26` branch to `0.26.0-rc.x+1` version.
  - Change the `Cargo.toml` version value to `0.26.0-rc.x+1`.
  - The commit message should be "Bump version to 0.26.0-rc.x+1".
- [x] Add a tag to the `HEAD` commit in the `release/0.26` branch.
  - The tag name should be `v0.26.0-rc.x+1`, where x is the current release candidate number.
  - Use tag message "Release 0.26.0 rc.x+1".
  - Make sure the tag is signed, for extra safety use the explicit `--sign` flag.
- [x] Push the new tag to the `bitcoindevkit/bdk` repo.
  - Use `git push --tags` option to push the new `v0.26.0-rc.x+1` tag.

#### On the day of the release

Tag and publish new release:

- [x] Bump the `release/0.26` branch to `0.26.0` version.
  - Change the `Cargo.toml` version value to `0.26.0`.
  - The commit message should be "Bump version to 0.26.0".
- [x] Add a tag to the `HEAD` commit in the `release/0.26` branch.
  - The tag name should be `v0.26.0`
  - The first line of the tag message should be "Release 0.26.0".
  - In the body of the tag message put a copy of the **Summary** and **Changelog** for the release.
  - Make sure the tag is signed, for extra safety use the explicit `--sign` flag.
- [x] Wait for the CI to finish one last time.
- [x] Push the new tag to the `bitcoindevkit/bdk` repo.
- [x] Publish **all** the updated crates to crates.io.
- [x] Create the release on GitHub.
  - Go to "tags", click on the dots on the right and select "Create Release".
  - Set the title to `Release 0.26.0`.
  - In the release notes body put the **Summary** and **Changelog**.
  - Use the "+ Auto-generate release notes" button to add details from included PRs.
  - Until we reach a `1.0.0` release check the "Pre-release" box.
- [x] Make sure the new release shows up on [crates.io] and that the docs are built correctly on [docs.rs].
- [x] Announce the release, using the **Summary**, on Discord, Twitter and Mastodon.
- [x] Celebrate 🎉

[Semantic Versioning]: https://semver.org/
[crates.io]: https://crates.io/crates/bdk
[docs.rs]: https://docs.rs/bdk/latest/bdk
["keep a changelog"]: https://keepachangelog.com/en/1.0.0/

**Comment by notmandatory** [comment]
Required downstream project updates:
- [x] bitcoindevkit/bdk-reserves#19
- [x] bitcoindevkit/bdk-cli#133
- [x] bitcoindevkit/bdk-ffi#288
