### ISSUE TITLE
Release 0.27.0

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#851]
### Summary

A maintenance release with a bump in project MSRV to 1.57.0, updated dependence and a few developer oriented improvements. Improvements include  better error formatting, don't default to async/await for wasm32 and adding derived PartialEq and Eq on SyncTime.

### Commit

553df318ff731c1e44014d015a6e61446d1c34ad

### Changelog

Changed

- Improve display error formatting #814
- Don't default to use async/await on wasm32 #831
- Project MSRV changed from 1.56.1 to 1.57.0 #842
- Update rust-miniscript dependency to latest bug fix release 9.0 #844

Added

- Derive PartialEq, Eq on SyncTime #837

### Checklist

Release numbering must follow [Semantic Versioning]. These steps assume the current `master`
branch **development** version is *0.26.0*.

#### On the day of the feature freeze

Change the `master` branch to the next MINOR+1 version:

- [x] Switch to the `master` branch.
- [x] Create a new PR branch called `bump_dev_0_27`.
- [x] Bump the `bump_dev_0_27` branch to the next development MINOR+1 version.
  - Change the `Cargo.toml` version value to `0.27.0`.
  - Update the `CHANGELOG.md` file.
  - The commit message should be "Bump version to 0.27.0".
- [x] Create PR and merge the `bump_dev_0_27` branch to `master`.
  - Title PR "Bump version to 0.27.0".

Create a new release branch and release candidate tag:

- [x] Double check that your local `master` is up-to-date with the upstream repo.
- [x] Create a new branch called `release/0.27` from `master`.
- [x] Bump the `release/0.27` branch to `0.27.0-rc.1` version.
  - Change the `Cargo.toml` version value to `0.27.0-rc.1`.
  - The commit message should be "Bump version to 0.27.0-rc.1".
- [x] Add a tag to the `HEAD` commit in the `release/0.27` branch.
  - The tag name should be `v0.27.0-rc.1`
  - Use message "Release 0.27.0 rc.1".
  - Make sure the tag is signed, for extra safety use the explicit `--sign` flag.
- [x] Push the `release/MAJOR.MINOR` branch and new tag to the `bitcoindevkit/bdk` repo.
  - Use `git push --tags` option to push the new `v0.27.0-rc.1` tag.

If any issues need to be fixed before the *0.27.0* version is released:

- [ ] Merge fix PRs to the `master` branch.
- [ ] Git cherry-pick fix commits to the `release/0.27` branch.
- [ ] Verify fixes in `release/0.27` branch.
- [ ] Bump the `release/0.27` branch to `0.27.0-rc.x+1` version.
  - Change the `Cargo.toml` version value to `0.27.0-rc.x+1`.
  - The commit message should be "Bump version to 0.27.0-rc.x+1".
- [ ] Add a tag to the `HEAD` commit in the `release/0.27` branch.
  - The tag name should be `v0.27.0-rc.x+1`, where x is the current release candidate number.
  - Use tag message "Release 0.27.0 rc.x+1".
  - Make sure the tag is signed, for extra safety use the explicit `--sign` flag.
- [ ] Push the new tag to the `bitcoindevkit/bdk` repo.
  - Use `git push --tags` option to push the new `v0.27.0-rc.x+1` tag.

#### On the day of the release

Tag and publish new release:

- [x] Bump the `release/0.27` branch to `0.27.0` version.
  - Change the `Cargo.toml` version value to `0.27.0`.
  - The commit message should be "Bump version to 0.270".
- [x] Add a tag to the `HEAD` commit in the `release/0.27` branch.
  - The tag name should be `v0.27.0`
  - The first line of the tag message should be "Release 0.27.0".
  - In the body of the tag message put a copy of the **Summary** and **Changelog** for the release.
  - Make sure the tag is signed, for extra safety use the explicit `--sign` flag.
- [x] Wait for the CI to finish one last time.
- [x] Push the new tag to the `bitcoindevkit/bdk` repo.
- [x] Publish **all** the updated crates to crates.io.
- [x] Create the release on GitHub.
  - Go to "tags", click on the dots on the right and select "Create Release".
  - Set the title to `Release 0.27.0`.
  - In the release notes body put the **Summary** and **Changelog**.
  - Use the "+ Auto-generate release notes" button to add details from included PRs.
  - Until we reach a `1.0.0` release check the "Pre-release" box.
- [x] Make sure the new release shows up on [crates.io] and that the docs are built correctly on [docs.rs].
- [x] Announce the release, using the **Summary**, on Discord, Twitter and Mastodon.
- [x] Celebrate 🎉

[Semantic Versioning]: https://semver.org/
[crates.io]: https://crates.io/crates/bdk
[docs.rs]: https://docs.rs/bdk/latest/bdk
["keep a changelog"]: https://keepachangelog.com/en/1.0.0/

**Comment by notmandatory** [comment]
Required downstream project updates:

- [x] bdk-reserves bitcoindevkit/bdk-reserves#20
- [x] bdk-cli bitcoindevkit/bdk-cli#143
- [x] bdk-ffi bitcoindevkit/bdk-ffi#308
- [x] wasm for playground in bitcoindevkit.org bitcoindevkit/bitcoindevkit.org#138

**Comment by thunderbiscuit** [comment]
The ffi has bumped to the official release and all tests have passed.
